version: "3.8"

services:
  # Reverse proxy with automatic HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: goldvision-caddy-staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.staging:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - EMAIL=${TLS_EMAIL:-admin@localhost}
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - goldvision-staging

  # PostgreSQL Database (staging)
  postgres:
    image: postgres:15-alpine
    container_name: goldvision-postgres-staging
    environment:
      POSTGRES_USER: goldvision
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: goldvision
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - goldvision-staging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goldvision"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: goldvision-backend-staging
    environment:
      NODE_ENV: production
      PORT: 8000
      DATABASE_URL: postgresql://goldvision:${POSTGRES_PASSWORD:-changeme}@postgres:5432/goldvision
      PROPHET_URL: http://prophet:8001
      NEWS_PROVIDER: ${NEWS_PROVIDER:-marketaux}
      NEWS_API_KEY: ${NEWS_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
      GOOGLE_SHEETS_API_KEY: ${GOOGLE_SHEETS_API_KEY}
      GOOGLE_SHEET_ID: ${GOOGLE_SHEET_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./prisma:/app/prisma
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      prophet:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/live"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      - goldvision-staging

  # Prophet service
  prophet:
    build:
      context: ./prophet-service
      dockerfile: Dockerfile
    container_name: goldvision-prophet-staging
    environment:
      PORT: 8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      - goldvision-staging

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: goldvision-frontend-staging
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://${DOMAIN:-localhost}}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - goldvision-staging

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus
    container_name: goldvision-prometheus-staging
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - goldvision-staging

  # Grafana dashboard
  grafana:
    image: grafana/grafana
    container_name: goldvision-grafana-staging
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana_data:/var/lib/grafana
      - ./monitoring/grafana_provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_SERVER_DOMAIN: ${DOMAIN:-localhost}
      GF_SERVER_ROOT_URL: https://${DOMAIN:-localhost}:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - goldvision-staging

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  prometheus_data:

networks:
  goldvision-staging:
    driver: bridge
