#!/usr/bin/env node

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ARTIFACTS_DIR = "artifacts/sbom";
const ALLOWED_LICENSES = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unlicense",
  "0BSD",
  "CC0-1.0",
  "MPL-2.0",
  "BlueOak-1.0.0",
  "CC-BY-4.0",
  "CC-BY-3.0",
  "Python-2.0",
  "UNLICENSED",
];

// Ensure artifacts directory exists
if (!fs.existsSync(ARTIFACTS_DIR)) {
  fs.mkdirSync(ARTIFACTS_DIR, { recursive: true });
}

function generateSBOM(serviceName, packageJsonPath, outputFile) {
  console.log(`📦 Generating SBOM for ${serviceName}...`);

  try {
    // Check if syft is available
    try {
      execSync("which syft", { stdio: "pipe" });
    } catch (error) {
      console.log(`⚠️  Syft not found, using npm audit for ${serviceName}`);
      generateNpmAuditSBOM(serviceName, packageJsonPath, outputFile);
      return;
    }

    // Generate SBOM with syft
    const command = `syft ${path.dirname(packageJsonPath)} -o spdx-json -q`;
    const output = execSync(command, { encoding: "utf8" });

    // Parse and enhance the SBOM
    const sbom = JSON.parse(output);
    sbom.metadata = {
      ...sbom.metadata,
      tool: {
        name: "syft",
        version: execSync("syft version", { encoding: "utf8" }).trim(),
      },
      service: serviceName,
      generated_at: new Date().toISOString(),
    };

    fs.writeFileSync(outputFile, JSON.stringify(sbom, null, 2));
    console.log(`✅ SBOM generated: ${outputFile}`);
  } catch (error) {
    console.error(
      `❌ Failed to generate SBOM for ${serviceName}:`,
      error.message
    );
    generateNpmAuditSBOM(serviceName, packageJsonPath, outputFile);
  }
}

function generateNpmAuditSBOM(serviceName, packageJsonPath, outputFile) {
  console.log(`📋 Generating npm audit SBOM for ${serviceName}...`);

  try {
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
    const dependencies = {
      ...packageJson.dependencies,
      ...packageJson.devDependencies,
    };

    const sbom = {
      spdxVersion: "SPDX-2.3",
      dataLicense: "CC0-1.0",
      SPDXID: "SPDXRef-DOCUMENT",
      name: `${serviceName}-sbom`,
      documentNamespace: `https://goldvision.com/sbom/${serviceName}-${Date.now()}`,
      packages: Object.entries(dependencies).map(([name, version], index) => ({
        SPDXID: `SPDXRef-${index + 1}`,
        name: name,
        versionInfo: version.replace(/[\^~]/, ""),
        downloadLocation: "NOASSERTION",
        filesAnalyzed: false,
        licenseConcluded: "NOASSERTION",
        licenseDeclared: "NOASSERTION",
        copyrightText: "NOASSERTION",
        description: `Package: ${name}@${version}`,
      })),
      metadata: {
        tool: {
          name: "npm-audit-sbom",
          version: "1.0.0",
        },
        service: serviceName,
        generated_at: new Date().toISOString(),
      },
    };

    fs.writeFileSync(outputFile, JSON.stringify(sbom, null, 2));
    console.log(`✅ npm audit SBOM generated: ${outputFile}`);
  } catch (error) {
    console.error(
      `❌ Failed to generate npm audit SBOM for ${serviceName}:`,
      error.message
    );
  }
}

function generateLicenseReport() {
  console.log("📄 Generating license report...");

  try {
    const command =
      "npx license-checker --json --out artifacts/licenses_report.json";
    execSync(command, { stdio: "inherit" });

    // Process the license report
    const licenseData = JSON.parse(
      fs.readFileSync("artifacts/licenses_report.json", "utf8")
    );
    const disallowedLicenses = [];
    const allowedLicenses = [];

    Object.entries(licenseData).forEach(([packageName, data]) => {
      const licenses = Array.isArray(data.licenses)
        ? data.licenses
        : [data.licenses];
      const hasAllowedLicense = licenses.some((license) =>
        ALLOWED_LICENSES.some((allowed) => license.includes(allowed))
      );

      if (hasAllowedLicense) {
        allowedLicenses.push({ package: packageName, licenses });
      } else {
        disallowedLicenses.push({ package: packageName, licenses });
      }
    });

    // Generate human-readable report
    const report = `# License Report - ${new Date().toISOString()}

## Summary
- Total packages: ${Object.keys(licenseData).length}
- Allowed licenses: ${allowedLicenses.length}
- Disallowed licenses: ${disallowedLicenses.length}

## Allowed Licenses
${allowedLicenses
  .map((pkg) => `- ${pkg.package}: ${pkg.licenses.join(", ")}`)
  .join("\n")}

## Disallowed Licenses
${disallowedLicenses
  .map((pkg) => `- ${pkg.package}: ${pkg.licenses.join(", ")}`)
  .join("\n")}

## License Policy
Allowed licenses: ${ALLOWED_LICENSES.join(", ")}

## Generated by
- Tool: license-checker
- Date: ${new Date().toISOString()}
- Service: GoldVision
`;

    fs.writeFileSync("artifacts/licenses_report.txt", report);
    console.log("✅ License report generated: artifacts/licenses_report.txt");

    // Check for disallowed licenses
    if (disallowedLicenses.length > 0) {
      console.log("⚠️  Disallowed licenses found:");
      disallowedLicenses.forEach((pkg) => {
        console.log(`  - ${pkg.package}: ${pkg.licenses.join(", ")}`);
      });
      process.exit(1);
    } else {
      console.log("✅ All licenses are allowed");
    }
  } catch (error) {
    console.error("❌ Failed to generate license report:", error.message);
    process.exit(1);
  }
}

function main() {
  console.log("🔒 Starting Supply Chain Security Analysis\n");

  // Generate SBOMs for each service
  generateSBOM(
    "backend",
    "package.json",
    path.join(ARTIFACTS_DIR, "backend-sbom.json")
  );
  generateSBOM(
    "frontend",
    "frontend/package.json",
    path.join(ARTIFACTS_DIR, "frontend-sbom.json")
  );
  generateSBOM(
    "prophet-service",
    "prophet-service/requirements.txt",
    path.join(ARTIFACTS_DIR, "prophet-service-sbom.json")
  );

  // Generate license report
  generateLicenseReport();

  console.log("\n🎉 Supply chain security analysis completed!");
  console.log("📁 SBOMs saved to: artifacts/sbom/");
  console.log("📄 License report: artifacts/licenses_report.txt");
}

if (require.main === module) {
  main();
}

module.exports = { generateSBOM, generateLicenseReport };
