/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the service is running and get basic system information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Get Prometheus metrics for monitoring and observability
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics in Prometheus format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI specification
         * @description Get the OpenAPI specification for this API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OpenAPI specification */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API documentation
         * @description Interactive API documentation using Swagger UI
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Swagger UI interface */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user and receive access and refresh tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Too many login attempts */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RateLimitResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get information about the currently authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Refresh the access token using a valid refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResponse"];
                    };
                };
                /** @description Invalid refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get gold prices
         * @description Retrieve historical gold price data with optional filtering and pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Start date for price data (YYYY-MM-DD) */
                    from?: string;
                    /** @description End date for price data (YYYY-MM-DD) */
                    to?: string;
                    /** @description Maximum number of prices to return */
                    limit?: number;
                    /** @description Cursor for pagination */
                    cursor?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Price data retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricesResponse"];
                    };
                };
                /** @description Invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest price data
         * @description Ingest new gold price data with validation and deduplication
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PriceIngestRequest"];
                };
            };
            responses: {
                /** @description Prices ingested successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PriceIngestResponse"];
                    };
                };
                /** @description Invalid data format or validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate price forecast
         * @description Generate gold price forecast using Prophet AI with circuit breaker protection
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ForecastRequest"];
                };
            };
            responses: {
                /** @description Forecast generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ForecastResponse"];
                    };
                };
                /** @description Insufficient data or invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forecast generation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decompose components (trend, weekly, yearly, holidays)
         * @description Fetch last 365 days and forward to Prophet components API.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ComponentsGatewayRequest"];
                };
            };
            responses: {
                /** @description Components returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComponentsGatewayResponse"];
                    };
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Component decomposition failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events: live prices
         * @description Stream live price ticks for asset/currency via SSE.
         */
        get: {
            parameters: {
                query?: {
                    asset?: "XAU";
                    currency?: "USD" | "YER";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream of tick events (text/event-stream) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get provider status
         * @description Get current status of the data provider including health and metrics
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Provider status retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/data-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get data source information
         * @description Get detailed information about the data source (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data source information retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DataSourceInfo"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get system metrics
         * @description Get detailed system metrics and performance data (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get scheduler status
         * @description Get information about the automated scheduler (admin only)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Scheduler status retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SchedulerStatus"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Admin access required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user alerts
         * @description Get all alerts for the authenticated user
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alerts retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertsResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create alert
         * @description Create a new price alert for the authenticated user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlertRequest"];
                };
            };
            responses: {
                /** @description Alert created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                /** @description Invalid alert data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download evidence pack
         * @description Download the latest evidence pack as a ZIP file
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evidence pack downloaded successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/zip": string;
                    };
                };
                /** @description No artifacts found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Monte Carlo simulation
         * @description Run Monte Carlo simulation for risk analysis with VaR and CVaR calculations
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulationRequest"];
                };
            };
            responses: {
                /** @description Simulation completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationResponse"];
                    };
                };
                /** @description Invalid simulation parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Simulation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ComponentTrend: {
            /** Format: date */
            ds: string;
            value: number;
        };
        ComponentWeekly: {
            dow: number;
            label: string;
            value: number;
        };
        ComponentYearly: {
            doy: number;
            /** Format: date */
            ds: string;
            value: number;
        };
        ComponentHoliday: {
            /** Format: date */
            ds: string;
            name: string;
            value: number;
        };
        ComponentsGatewayRequest: {
            /**
             * @default XAU
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "YER";
            options?: {
                yearly_seasonality?: boolean;
                weekly_seasonality?: boolean;
                holidays?: boolean;
                /** @enum {string} */
                seasonality_mode?: "additive" | "multiplicative";
            };
        };
        ComponentsGatewayResponse: {
            asset: string;
            currency: string;
            trend: components["schemas"]["ComponentTrend"][];
            weekly: components["schemas"]["ComponentWeekly"][];
            yearly: components["schemas"]["ComponentYearly"][];
            holidays?: components["schemas"]["ComponentHoliday"][] | null;
            /** @enum {string} */
            seasonality_mode: "additive" | "multiplicative";
            /** Format: date-time */
            generated_at: string;
        };
        HealthResponse: {
            /** @example ok */
            status: string;
            /** Format: date-time */
            timestamp: string;
            uptime_seconds: number;
            version: string;
            prophet_healthy?: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            access_token: string;
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        RefreshRequest: {
            refresh_token: string;
        };
        RefreshResponse: {
            access_token: string;
            refresh_token: string;
        };
        User: {
            id: number;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "user" | "admin";
            /** @enum {string} */
            locale: "en" | "ar";
        };
        PriceData: {
            /** Format: date */
            ds: string;
            price: number;
            /**
             * @description Asset type (Gold, Silver, Platinum)
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency code
             * @enum {string}
             */
            currency: "USD" | "YER";
        };
        PricesResponse: {
            prices: components["schemas"]["PriceData"][];
            count: number;
            total_count: number;
            next_cursor?: number | null;
        };
        PriceIngestRequest: {
            rows: components["schemas"]["PriceData"][];
        };
        PriceIngestResponse: {
            message: string;
            count: number;
            /** Format: date-time */
            ingested_at: string;
        };
        ForecastRequest: {
            /**
             * @description Asset to forecast (Gold, Silver, Platinum)
             * @default XAU
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency for the forecast
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "YER";
            /** @default 14 */
            horizon_days: number;
            /**
             * @description Include historical data in response
             * @default false
             */
            include_history: boolean;
        };
        ForecastPoint: {
            /** Format: date */
            ds: string;
            yhat: number;
            yhat_lower: number;
            yhat_upper: number;
        };
        ForecastResponse: {
            /** Format: date-time */
            generated_at: string;
            horizon_days: number;
            /**
             * @description Asset forecasted
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency used
             * @enum {string}
             */
            currency: "USD" | "YER";
            forecast: components["schemas"]["ForecastPoint"][];
            /** @description Historical data (if requested) */
            history?: components["schemas"]["PriceData"][];
            model_version?: string;
            training_window_days?: number;
            holidays_enabled?: boolean;
            seasonality_flags?: Record<string, never>;
            /** @description True if forecast was generated using fallback method */
            degraded?: boolean;
        };
        ProviderStatus: {
            /** @enum {string} */
            status: "active" | "inactive" | "error";
            /** Format: date-time */
            last_fetch_at?: string | null;
            last_price?: {
                /** Format: date */
                ds?: string;
                price?: number;
            } | null;
            retries_last_run: number;
            fallback_used_last_run: boolean;
            scheduler_interval_min: number;
        };
        DataSourceInfo: {
            status: string;
            /** Format: date-time */
            last_fetch_at?: string | null;
            last_price?: {
                /** Format: date */
                ds?: string;
                price?: number;
            } | null;
            retries_last_run: number;
            fallback_used_last_run: boolean;
        };
        SchedulerStatus: {
            /** @enum {string} */
            status: "running" | "stopped" | "error";
            interval_minutes: number;
            /** Format: date-time */
            next_run: string;
            tasks: {
                [key: string]: {
                    status?: string;
                    /** Format: date-time */
                    last_run?: string;
                    /** Format: date-time */
                    next_run?: string;
                };
            };
        };
        Alert: {
            id: number;
            /**
             * @description Asset for the alert
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency for the alert
             * @enum {string}
             */
            currency: "USD" | "YER";
            /** @enum {string} */
            rule_type: "price_threshold" | "price_change" | "volume_threshold";
            threshold: number;
            /** @enum {string} */
            direction: "above" | "below" | "change_up" | "change_down";
            /** Format: date-time */
            triggered_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CreateAlertRequest: {
            /**
             * @description Asset for the alert
             * @default XAU
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency for the alert
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "YER";
            /** @enum {string} */
            rule_type: "price_above" | "price_below";
            threshold: number;
            /** @enum {string} */
            direction: "above" | "below";
        };
        AlertsResponse: {
            alerts: components["schemas"]["Alert"][];
            count: number;
        };
        SimulationRequest: {
            /**
             * @description Asset to simulate (Gold, Silver, Platinum)
             * @default XAU
             * @enum {string}
             */
            asset: "XAU";
            /**
             * @description Currency for the simulation
             * @default USD
             * @enum {string}
             */
            currency: "USD" | "YER";
            /**
             * @description Number of days to simulate
             * @default 30
             */
            days: number;
            /**
             * @description Simulation method (Geometric Brownian Motion or Bootstrap)
             * @default gbm
             * @enum {string}
             */
            method: "gbm" | "bootstrap";
            /** @description Annual volatility percentage (GBM only) */
            annual_vol?: number | null;
            /** @description Annual drift adjustment percentage */
            drift_adj?: number | null;
            /**
             * @description Number of simulation paths
             * @default 10000
             */
            n: number;
        };
        SimulationPoint: {
            /**
             * Format: date
             * @description Date string in YYYY-MM-DD format
             */
            ds: string;
            /** @description 1st percentile */
            p01: number;
            /** @description 5th percentile */
            p05: number;
            /** @description 10th percentile */
            p10: number;
            /** @description 50th percentile (median) */
            p50: number;
            /** @description 90th percentile */
            p90: number;
            /** @description 95th percentile */
            p95: number;
            /** @description 99th percentile */
            p99: number;
        };
        SimulationResponse: {
            /** @description Simulation method used */
            method: string;
            /** @description Number of days simulated */
            days: number;
            /** @description Number of paths generated */
            n: number;
            /** @description Random seed used */
            seed: number;
            /** @description Asset simulated */
            asset: string;
            /** @description Currency used */
            currency: string;
            /** @description Fan chart data with percentiles for each day */
            fan: components["schemas"]["SimulationPoint"][];
            /** @description Value at Risk at 95% confidence level */
            var95: number;
            /** @description Conditional Value at Risk at 95% confidence level */
            cvar95: number;
        };
        ErrorResponse: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            request_id?: string | null;
        };
        RateLimitResponse: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            retry_after: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
